# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6af653b82601e19c6e67134bd9091c4767d24d86a2ee396b1e8d59fd92a4a2856217706fbe53a5b2d56652eb8ce941afafbc384d57a5a536ce32ef6cd8b026db

test:
  secret_key_base: b3bc8f927145bc94b2d7757810278f76ad9df16810ff8e2925ad6737c41862cebeeb4e45c54a4f04498a5a538b0b0711a3381d7df1565ad2ed01fcab08a33630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
